---
- name: implementing loops
  hosts: all
  tasks:
   - name:  uninstall softwares
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: git,b: absent,c: no}
      - {a: maven,b: absent,c: no}
      - {a: firewalld,b: absent,c: no}        
