---
- name: create multiple users and copy files into their home directory
  hosts: all
  tasks:
   - name: create multiple users
     user: 
      name: "{{item.a}}"
      password: "{{item.b}}"
      uid: "{{item.c}}"
      home: "{{item.d}}"
     with_items: 
      - {a: kisan,b: intelliqit,c: 6789,d: /home/ubuntu/kisan}
      - {a: rao,b: intelliqit,c: 7890,d: /home/rao}
   
   - name: copy passwd file and group file 
     copy:
      src: "{{item.a}}"
      dest: "{{item.b}}"
     with_items:
       - {a: /etc/passwd,b: /home/ubuntu/kisan}
       - {a: /etc/group,b: /home/rao}         
