---
- name: implementing loops
  hosts: all
  tasks:
   - name: installing softwares
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - git
      - maven
      - firewalld
      - tree        
