---
- name: download docker images
  hosts: all
  tasks:
   - name: pull mulitple docker images
     docker_image:
             name: "{{item}}"
     with_items:
             - ubuntu
             - centos
             - busybox
             - alpine         

