---
- name: creating 10 nginx container using load balanceing
  hosts: all
  tasks:
   - name: create 10 containers
     docker_container:
             image: nginx
             name: "container{{item}}"
     with_sequence: count=10        
