---
- name: create an ubuntu container and mount a volume
  hosts: all
  tasks:
   - name: create a ubuntu container
     docker_container:
       image: ubuntu
       name: myubuntu
       volumes:
               - /data1
       interactive: yes
       tty: yes       


