---
- name: working on docker containers
  hosts: all
  tasks:
   - name: start a httpd container
     docker_container:
             image: httpd
             name: appserver
             ports: 
              - 7070:80  
   - name: stop a httpd container
     docker_container:
      name: appserver
      state: stopped 
   - name: remove a httpd container
     docker_container:
       name: appserver
       state: absent         
