---
- name: setup of docker
  hosts: all
  tasks:
   - name: install python-pip
     apt: 
      name: python-pip
      state: present
      update_cache: yes
   - name: download docker
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip install docker-py         
